logging:
  config: classpath:logback-spring.xml
  path: /home/hole/logs

server:
  port: 443
  ssl:
      key-store: classpath:myhole.jks
      key-password: 1533746520548
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.174.56/hole_system?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123@PHz3gqLN3g
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true